apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: cloudmart-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8090
          env:
            - name: EUREKA_URL
              value: http://eureka:8761/eureka/
            - name: JAVA_OPTS
              value: "-Xmx128m -Xms64m"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30090
